### ISSUE TITLE
CODT向けのCDを設定する

### ISSUE THREAD

**Issue by takaishi** [cloudnativedaysjp/dreamkast-kanban#22]
# Goal

CODT用のdreamkastやdreamkast-uiについて、stagingへの自動デプロイとproduictionへのReleaseBotを使ったデプロイが可能であること

**Comment by ShotaKitazawa** [comment]
releasebot は codt-dreamkast-prd-cluster EKS で動作させ、SlackBot は cloudopsdays.slack.com にインストールします。

**Comment by ShotaKitazawa** [comment]
### TODO (CODT タスク)

* [x] cert-manager, external-secrets がデプロイ出来ない問題を解決する
    * ~~共通点は ArgoCD から Helm でデプロイしてることなので、これが原因？~~
    * argocd-application-controller の resources を一切設定していなかったことが原因
        * Fargate Node が NotReady になっていた
* [x] Route53 にサブドメインを委譲してもらう (`event.cloudopsdays.com`)
* [x] cert-manager で *.event.cloudopsdays.com 用の証明書を取得
    * cert-manager-webhook の待受が 10250 で、Fargate 利用してるので kubelet と競合していた → 10260 で待ち受けるようにした
* [x] ArgoCD にて利用する auth0 の redirect url に argocd.event.cloudopsdays.com を指定
* [x] secret manager に任意の値を登録
    * dreamkast, dreamkast-ui 用 → 他チケットにて実施
    * releasebot 用 → 当チケットにて実施
* [ ] releasebot を CODT 側 Slack にインストールして、リリースフローが動作することを確認

**Comment by ShotaKitazawa** [comment]
### TODO (dreamkast-infra 全般)

以下はこのチケットのスコープ外だが、思いついたのでメモ書きしておく

* gitops in GitHub Actions (CI トリガでマニフェストを更新) → argocd-image-updater (container registry 上のイメージ更新トリガでマニフェストを更新) への移行
    * GitOps 用にマニフェストを編集するのを CI Ops ではなく CD Ops 的に扱えるので良い (個人的な感想)
    * 今回みたいにリポジトリを fork したときも、後者のほうがおそらく混乱が少ない
    * GitHub Actions に依存しなくなる (まれによく障害が起こって困る)
* リポジトリに push されてない infra マニフェストの配置
    * metrics-server, cloudwatch など (TODO: リストアップ)
* セットアップ手順属人化問題の解決
    * 最初に何のコマンドを叩くかの手順がないので README とかに起こす
    * argocd-secret が手元にしか無いのでどうにかする
* Container Registry の public 化
    * 今回の CODT みたいに別 AWS プロジェクトに環境を複製となった時に、本流の image を pull できない

**Comment by ShotaKitazawa** [comment]
* releasebot は Legacy Bot が新規作成できなくなってしまったため、当チケットでの導入は諦める。
* CODT では releasebot の代わりに tag push で stg → prd への promote を実施する。
* releasebot の RTM → event API 化は CND 側の別タスクにて実施

**Comment by ShotaKitazawa** [comment]
ひとまず、以下の案を取ることで CODT の dev,stg,prd 向け CD 設定は一通り動いてそうなので、チケットクローズします。

> releasebot は Legacy Bot が新規作成できなくなってしまったため、当チケットでの導入は諦める。
> CODT では releasebot の代わりに tag push で stg → prd への promote を実施する。
> releasebot の RTM → event API 化は CND 側の別タスクにて実施
